name = "Vault Hunters 3rd Edition"
version = "3.10.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ac850387179ea37aedcc8ac265301ee60e6f5bac97b59082db1b90e698bfac9"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
