name = "Vault Hunters 3rd Edition"
version = "3.10.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e8b3f4db0488dcc3ac86885cc0abfdb42be56ed477d573d8aeef2cb424280a9"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
